### PR TITLE
Add tribool support

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by saraedum** [comment]
@videlec, does this look good to you?

**Comment by videlec** [comment]
I would rather use `true`/`false`/`indeterminate` (all lower case) as it prints in C++.

I noticed a `safe_bool` function in `boost::logic::tribool`. Could we have access to that?

**Review by videlec — CHANGES_REQUESTED** [review]
beyond printing everything looks fine

**Comment by saraedum** [comment]
`safe_bool` should  be identical to just saying `bool(x)` in Python. Essentially, it returns `true` if the tribool is true and false otherwise. (safe_bool is a pre-C++11 way of implementing a bool conversion without getting into trouble with implicit conversions…)

**Review by videlec — APPROVED** [review]

**Pull request merged**
